databases:
  - name: bbkits-db
    plan: free
    databaseName: bbkits
    user: bbkits

services:
  - type: web
    name: bbkits
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_KEY
        generateValue: true
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        fromService:
          type: web
          name: bbkits
          property: host
      - key: LOG_CHANNEL
        value: stack
      - key: LOG_LEVEL
        value: error
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: bbkits-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: bbkits-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: bbkits-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: bbkits-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: bbkits-db
          property: password
      - key: BROADCAST_DRIVER
        value: log
      - key: CACHE_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: SESSION_DRIVER
        value: file
      - key: SESSION_LIFETIME
        value: 120
      - key: MEMCACHED_HOST
        value: 127.0.0.1
      - key: MAIL_MAILER
        value: log
      - key: MAIL_HOST
        value: mailhog
      - key: MAIL_PORT
        value: 1025
      - key: MAIL_USERNAME
        value: null
      - key: MAIL_PASSWORD
        value: null
      - key: MAIL_ENCRYPTION
        value: null
      - key: MAIL_FROM_ADDRESS
        value: hello@bbkits.com
      - key: MAIL_FROM_NAME
        value: BBKits